[project]
name = "natricine-redisstream"
version = "0.2.0"
description = "Redis Streams backend for natricine"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "msgpack>=1.1.2",
    "natricine",
    "redis>=5.0",
]

[project.optional-dependencies]
test = ["pytest", "pytest-anyio", "testcontainers[redis]"]

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "natricine_redis"
